account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', signin, name="login"),
    path('signout', signout, name="signout"),
    path('signup', signup, name="signup"),
    path('change-password', change_password, name="change-password"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('email-activation/', email_message, name="email-activation"),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import signin, signup, signout, change_password, password_reset_request, email_message

app_name = "accounts"   # App name for calling Url's in template/Html

urlpatterns = [
    path('', signin, name="login"),
    path('signout', signout, name="signout"),
    path('signup', signup, name="signup"),
    path('change-password', change_password, name="change-password"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('email-activation/', email_message, name="email-activation"),
]

core/urls.py
from django.urls import path
from .views import index, BlogList, BlogDetail, UserProfile, EditProfile, Explore, UploadContent, Contact

app_name = 'core'

urlpatterns = [
    path('', index, name='home'),
    path('explore', Explore, name='explore'),
    path('contact-us', Contact, name='contact'),
    path('upload', UploadContent, name='content'),
    path('blog-list', BlogList, name='bloglist'),
    path('user-profile/', UserProfile, name='profile'),
    path('blog-detail/<int:id>/', BlogDetail, name='blogdetail'),
    path('edit-profile/', EditProfile, name='editprofile'),
]

cranft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('summernote/', include('django_summernote.urls')),
                  path('', include('core.urls')),
                  path('verification/', include('verify_email.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(
                           template_name='accounts/password/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(
                           template_name="accounts/password/password_reset_confirm.html"),
                       name='password_reset_confirm'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='accounts/password/password_reset_complete.html'),
                       name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class Profile(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)
    Image = models.ImageField(upload_to='profile_images/', verbose_name="Profile Picture")
    Cover = models.ImageField(upload_to='cover_images/', verbose_name="Cover Picture", null=True, blank=True)
    PhoneNumber = PhoneNumberField()
    Tagline = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.User} {self.PhoneNumber}'

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class RegisterForm(UserCreationForm):  # Modelform for registration
    username = forms.CharField(max_length=123, required=True)
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "email")

account/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from verify_email.email_handler import send_verification_email

from .forms import RegisterForm, ProfileForm

from django.http import HttpResponse


# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return HttpResponse('already authenticated')
        # return redirect('core:home')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        pform = ProfileForm(request.POST)
        print('post request')
        if form.is_valid() and pform.is_valid():
            print('form valid')
            inactive_user = send_verification_email(request, form)  # Send verification email to in-active user
            pinst = pform.save(commit=False)
            pinst.User = inactive_user
            pinst.save()
            return redirect('account:email-activation')
        else:
            print('form invalid')
            return render(request, 'accounts/signup.html', {'form': form, 'pform': pform})
    else:
        print('not post request')
        form = RegisterForm()
        pform = ProfileForm
        return render(request, 'accounts/signup.html', {'form': form, 'pform': pform})


def signin(request):
    error = ''
    if request.user.is_authenticated:
        # return redirect('core:home')
        return HttpResponse('already authenticated')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)  # authenticate user's, email and password
        if user is not None:
            login(request, user)
            return HttpResponse('signin')
            # return redirect('core:home')
        else:
            error = 'Invalid Username or Password'
            form = AuthenticationForm(request.POST)
            return render(request, 'accounts/login.html', {'form': form, 'error': error})
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def signout(request):
    logout(request)
    return redirect('account:login')


def password_reset_request(request):  # password reset for loged-out user
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']  # get user entered email
            associated_users = User.objects.filter(Q(email=data))  # find associated user with that email
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.txt"  # email body stored in txt file
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)  # All email data rendered as string
                    try:
                        send_mail(subject, email, 'quantchefin@gmail.com', [user.email],
                                  fail_silently=True)  # Send Email
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


@login_required
def change_password(request):  # change password for logged-in user
    message = ''
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # converting password to hash
            message = 'Password changed successfully'
            return redirect('core:home')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'accounts/password/password_reset_confirm.html', {'form': form, 'message': message})


def email_message(request):  # Show a message after signup process, to check email for verification
    return render(request, 'accounts/email_message.html')

accounts/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from .forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

# email verification
from verify_email.email_handler import send_verification_email

from .models import Profile


def signup(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        phonenumber = request.POST.get('PhoneNumber')
        if form.is_valid():
            inactive_user = send_verification_email(request, form)  # Send verification email to in-active user
            request.session['email'] = inactive_user.email  # save email in session, to add the same email for person
            Profile.objects.create(User=inactive_user, PhoneNumber=phonenumber)
            return redirect('accounts:email-activation')
        else:
            return render(request, 'accounts/signup.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'accounts/signup.html', {'form': form})


def signin(request):
    error = ''
    if request.user.is_authenticated:
        return redirect('core:profile')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)  # authenticate user's, email and password
        print(user)
        if user is not None:
            login(request, user)
            return redirect('core:profile')
        else:
            error = 'Invalid Username or Password'
            form = AuthenticationForm(request.POST)
            return render(request, 'accounts/login.html', {'form': form, 'error': error})
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})


def signout(request):
    logout(request)
    return redirect('accounts:login')


def password_reset_request(request):  # password reset for loged-out user
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']  # get user entered email
            associated_users = User.objects.filter(Q(email=data))  # find associated user with that email
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.txt"  # email body stored in txt file
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)  # All email data rendered as string
                    try:
                        send_mail(subject, email, 'panda.throwawayyy@gmail.com', [user.email],
                                  fail_silently=True)  # Send Email
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


@login_required
def change_password(request):  # change password for logged-in user
    message = ''
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # converting password to hash
            message = 'Password changed successfully'
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'core/change-password.html', {'form': form, 'message': message})


def email_message(request):  # Show a message after signup process, to check email for verification
    return render(request, 'accounts/email_message.html')

templates/accounts/email_meesage.html
{% extends 'base2.html.html' %}
{% load static %}
{% block content %}
    <section class="flexbox-container">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <div class="col-lg-4 col-md-6 col-10 box-shadow-2 p-0">
                <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                    <div class="card-header border-0">
                        <div class="text-center mb-1">
                            <img src="app-assets/images/logo/logo.png" alt="branding logo">
                        </div>
                        <div class="font-large-1  text-center">
                            Email Verification!
                        </div>
                    </div>
                    <div class="card-content">

                        <div class="card-body">
                            <h4 class="text-center">
                                <p>We have sent you a verification email,
                                    <br>
                                    please click on the link provided in the email to verify your account,
                                    <br>
                                    Check spam folder too.
                                </p>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/accounts/email_message.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <section class="flexbox-container">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <div class="col-lg-4 col-md-6 col-10 box-shadow-2 p-0">
                <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                    <div class="card-header border-0">
                        <div class="text-center mb-1">
                            <img src="app-assets/images/logo/logo.png" alt="branding logo">
                        </div>
                        <div class="font-large-1  text-center">
                            Email Verification!
                        </div>
                    </div>
                    <div class="card-content">

                        <div class="card-body">
                            <h4 class="text-center">
                                <p>We have sent you a verification email,
                                    <br>
                                    please click on the link provided in the email to verify your account,
                                    <br>
                                    Check spam folder too.
                                </p>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/accounts/error_file.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }} - {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }} - {{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/accounts/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }} - {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }} - {{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/accounts/login.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
    <section class="breadcrumb-area overlay-dark d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breamcrumb Content -->
                    <div class="breadcrumb-content text-center">
                        <h2 class="m-0">Login</h2>
                        <ol class="breadcrumb d-flex justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                            <li class="breadcrumb-item active">Login</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcrumb Area End ***** -->

    <!-- ***** Login Area Start ***** -->
    <section class="author-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-8 col-lg-7">
                    <!-- Intro -->
                    <div class="intro text-center">
                        <span>Login</span>
                        <h3 class="mt-3 mb-0">Login to your Account</h3>
{#                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae#}
{#                            quo ad iste ipsum officiis deleniti asperiores sit.</p>#}
                    </div>
                    <!-- Item Form -->
                    <form method="post" class="item-form card no-hover">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    <input type="text" class="form-control" name="username"
                                           placeholder="Enter your Username" required="required">
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    <input type="password" class="form-control" name="password"
                                           placeholder="Enter your Password" required="required">
                                </div>
                            </div>
                             <div class="col-12">
                                <span class="d-block text-center mt-4">Forgot Password? <a
                                        href="{% url 'accounts:password_reset' %}">Click here</a></span>
                            </div>
                            <div class="col-12">
                                <button class="btn w-100 mt-3 mt-sm-4" type="submit">Sign In</button>
                            </div>
                            <div class="col-12">
                                <span class="d-block text-center mt-4">Don't have an account? <a
                                        href="{% url 'accounts:signup' %}">Signup</a></span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Login Area End ***** -->
{% endblock %}

templates/accounts/signup.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
    <section class="breadcrumb-area overlay-dark d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breamcrumb Content -->
                    <div class="breadcrumb-content text-center">
                        <h2 class="m-0">Signup</h2>
                        <ol class="breadcrumb d-flex justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                            <li class="breadcrumb-item active">Signup</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcrumb Area End ***** -->

    <!-- ***** Signup Area Start ***** -->
    <section class="author-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-8 col-lg-7">
                    <!-- Intro -->
                    <div class="intro text-center">
                        <span>Signup</span>
                        <h3 class="mt-3 mb-0">Create an Account</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum obcaecati dignissimos quae
                            quo ad iste ipsum officiis deleniti asperiores sit.</p>
                    </div>
                    <!-- Item Form -->
                    <form method="post" class="item-form card no-hover">
                        {% csrf_token %}
                        {% include 'accounts/form_errors.html' %}
                        <div class="row">
                            {{ form.as_p }}
                            {{ pform.as_p }}
{#                            <div class="col-12">#}
{#                                <div class="form-group mt-3">#}
{#                                    <input type="text" class="form-control" name="username"#}
{#                                           placeholder="Enter your User Name"#}
{#                                           required="required">#}
{#                                    {{ form.username }}#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="col-12">#}
{#                                <div class="form-group mt-3">#}
{#                                    <input type="email" class="form-control" name="email" placeholder="Enter your Email"#}
{#                                           required="required">#}
{#                                    {{ form.email }}#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="col-12">#}
{#                                <div class="form-group mt-3">#}
{#                                    <input type="password" class="form-control" name="password1"#}
{#                                           placeholder="Enter your Password" required="required">#}
{#                                                                {{ form.password1 }}#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="col-12">#}
{#                                <div class="form-group mt-3">#}
{#                                    <input type="password" class="form-control" name="password2"#}
{#                                           placeholder="Renter your Password" required="required">#}
{#                                                                {{ form.password2 }}#}
{##}
{#                                </div>#}
{#                            </div>#}
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    <input type="tel" class="form-control" name="PhoneNumber"
                                           placeholder="Enter Your PhoneNumber" required="required">
                                </div>
                            </div>
{#                            <div class="col-12">#}
{#                                <div class="form-group mt-3">#}
{#                                    <div class="form-check form-check-inline">#}
{#                                        <input class="form-check-input" type="radio" name="inlineRadioOptions"#}
{#                                               id="inlineRadio1" value="option1">#}
{#                                        <label class="form-check-label" for="inlineRadio1">I agree to <a href="#">Privacy#}
{#                                            Policy</a></label>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
                            <div class="col-12">
                                <button class="btn w-100 mt-3 mt-sm-4" type="submit">Sign Up</button>
                            </div>
                            <div class="col-12">
                                <span class="d-block text-center mt-4">Already have an account? <a
                                        href="{% url 'accounts:login' %}">Login</a></span>
                            </div>
{#                            <div class="col-12">#}
{#                                <hr>#}
{#                                <div class="other-option">#}
{#                                    <span class="d-block text-center mb-4">Or</span>#}
{#                                    <!-- Social Icons -->#}
{#                                    <div class="social-icons d-flex justify-content-center">#}
{#                                        <a class="facebook" href="#">#}
{#                                            <i class="fab fa-facebook-f"></i>#}
{#                                            <i class="fab fa-facebook-f"></i>#}
{#                                        </a>#}
{#                                        <a class="twitter" href="#">#}
{#                                            <i class="fab fa-twitter"></i>#}
{#                                            <i class="fab fa-twitter"></i>#}
{#                                        </a>#}
{#                                        <a class="google-plus" href="#">#}
{#                                            <i class="fab fa-google-plus-g"></i>#}
{#                                            <i class="fab fa-google-plus-g"></i>#}
{#                                        </a>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Signup Area End ***** -->
{% endblock %}