accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import signin, signup, signout, change_password, password_reset_request, email_message

app_name = "accounts"   # App name for calling Url's in template/Html

urlpatterns = [
    path('', signin, name="login"),
    path('signout', signout, name="signout"),
    path('signup', signup, name="signup"),
    path('change-password', change_password, name="change-password"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('email-activation/', email_message, name="email-activation"),
]

core/urls.py
from django.urls import path
from .views import index, BlogList, BlogDetail, UserProfile, EditProfile, Explore, UploadContent, Contact

app_name = 'core'

urlpatterns = [
    path('', index, name='home'),
    path('explore', Explore, name='explore'),
    path('contact-us', Contact, name='contact'),
    path('upload', UploadContent, name='content'),
    path('blog-list', BlogList, name='bloglist'),
    path('user-profile/', UserProfile, name='profile'),
    path('blog-detail/<int:id>/', BlogDetail, name='blogdetail'),
    path('edit-profile/', EditProfile, name='editprofile'),
]

cranft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('summernote/', include('django_summernote.urls')),
                  path('', include('core.urls')),
                  path('verification/', include('verify_email.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(
                           template_name='accounts/password/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(
                           template_name="accounts/password/password_reset_confirm.html"),
                       name='password_reset_confirm'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='accounts/password/password_reset_complete.html'),
                       name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Videos(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    Video = models.FileField(upload_to='videos')
    width = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    Date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.User}'

    class Meta:
        verbose_name = 'Content'
        verbose_name_plural = 'Content'


class Blog(models.Model):
    Date = models.DateField(auto_now_add=True)

    Title = models.CharField(max_length=5000)
    Image = models.ImageField(upload_to='blog_images/', default='blog_images/default.png')
    Tagline = models.CharField(max_length=150, null=False, blank=False)

    Content = models.TextField(null=False, blank=False)
    Author = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return f'{self.Date} {self.Title}'

    def get_absolute_url(self):
        return reverse('core:blogdetail', args=f'{self.id}')

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'


class Contact(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField()
    subject = models.CharField(max_length=300)
    message = models.TextField()

    def __str__(self):
        return f'{self.name} {self.subject}'

    class Meta:
        verbose_name = 'Queries'
        verbose_name_plural = 'Queries'

core/forms.py
from django import forms
from .models import Videos, Contact
from accounts.models import Profile


class ContentForm(forms.ModelForm):
    class Meta:
        model = Videos
        exclude = ('User', 'width', 'height')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {'class': 'form-control', 'placeholder': 'Your Name',}
        self.fields['email'].widget.attrs = {'class': 'form-control', 'placeholder': 'Your Email',}
        self.fields['subject'].widget.attrs = {'class': 'form-control', 'placeholder': 'Subject',}
        self.fields['message'].widget.attrs = {'class': 'form-control', 'placeholder': 'Message',}


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("Image", "PhoneNumber", "Tagline", "Cover")

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['PhoneNumber'].widget.attrs = {'class': 'form-control',  'placeholder': 'Contact Number',}
        self.fields['Tagline'].widget.attrs = {'class': 'form-control', 'placeholder': 'Tag Line', }

core/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import ContentForm, ProfileForm, ContactForm
from accounts.models import Profile
from django.core.files.images import get_image_dimensions


# Create your views here.

def index(request):
    return render(request, 'core/index.html')


def BlogList(request):
    queryset = Blog.objects.all()
    context = {
        'obj': queryset,
    }
    return render(request, 'core/blog_list.html', context)


def BlogDetail(request, id):
    queryset = Blog.objects.get(id=id)
    context = {
        'obj': queryset,
    }
    return render(request, 'core/blog_detail.html', context)


@login_required()
def UserProfile(request):
    ProfilePicture = Profile.objects.get(User=request.user)
    Picture = ProfilePicture.Image
    Cover = ProfilePicture.Cover
    queryset = Videos.objects.filter(User=request.user)
    print(queryset)
    context = {
        'profile': Picture,
        'cover': Cover,
        'obj': queryset,
    }
    return render(request, 'core/profile.html', context)


@login_required()
def EditProfile(request):
    profile = Profile.objects.get(User=request.user)
    if request.method == 'POST':
        form2 = ProfileForm(request.POST, request.FILES, instance=profile)
        if form2.is_valid():
            content = form2.save(commit=False)
            content.User = request.user
            content.save()
            return redirect('core:profile')
    else:
        form2 = ProfileForm(instance=profile)
    context = {
        'form': form2,
    }
    return render(request, 'core/edit_profile.html', context)


def Explore(request):
    queryset = Videos.objects.all()
    print(queryset)
    context = {
        'obj': queryset,
    }
    return render(request, 'core/explore.html', context)


@login_required()
def UploadContent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            content = form.save(commit=False)
            content.User = request.user
            content.save()
            obj = Videos.objects.get(pk=content.pk)
            width, height = get_image_dimensions(obj.Video.file)
            obj.width = width
            obj.height = height
            obj.save()
            return redirect('core:profile')
    else:
        form = ContentForm
    context = {
        'form': form,
    }
    return render(request, 'core/content.html', context)


def Contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:home')
    else:
        form = ContactForm
    context = {
        'form' : form,
    }
    return render(request, 'core/contact.html', context)

templates/core/blog_detail.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}

        <!-- ***** Breadcrumb Area Start ***** -->
        <section class="breadcrumb-area overlay-dark d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Breamcrumb Content -->
                        <div class="breadcrumb-content text-center">
                            <h2 class="m-0">Blog Single</h2>
                            <ol class="breadcrumb d-flex justify-content-center">
                                <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                                <li class="breadcrumb-item active">Blog</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Breadcrumb Area End ***** -->

        <!-- ***** Blog Single Area Start ***** -->
        <section class="single featured post-details">
            <div class="container">
                <div class="row">
                    <!-- Main -->
                    <div class="col-12 col-lg-12 p-0">
                        <div class="row">
                            <div class="col-12 align-self-center">
                                <!-- Image -->
                                <div class="blog-thumb">
                                    <img class="w-100" src="{{ obj.Image.url }}" alt="">
                                </div>
                                <h2 class="featured ml-0">{{ obj.Title }}</h2>
                                {{ obj.Content|safe }}
                                <!-- Post Holder -->
                                <ul class="mb-5 post-holder">
                                    <li class="post-meta-item">
                                        <div class="date">
                                            <span class="posted-on">Posted On <a href="#" rel="bookmark"><time class="entry-date published updated" datetime="2018-11-01T06:18:46+00:00">{{ obj.Date }}</time></a></span>
                                        </div>
                                    </li>
                                </ul>

                                <!-- Comments -->
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </section>
        <!-- ***** Blog Single Area End ***** -->

{% endblock %}

templates/core/blog_list.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}

    <!-- ***** Breadcrumb Area Start ***** -->
    <section class="breadcrumb-area overlay-dark d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breamcrumb Content -->
                    <div class="breadcrumb-content text-center">
                        <h2 class="m-0">Blog</h2>
                        <ol class="breadcrumb d-flex justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                            <li class="breadcrumb-item active">Blog</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcrumb Area End ***** -->

    <!-- ***** Blog Area Start ***** -->
    <section class="blog-area load-more">
        <div class="container">
            <div class="row items">
                {% for obj in obj %}

                    <div class="col-12 col-md-4 item">
                        <!-- Single Blog -->
                        <div class="card blog-card">
                            <!-- Blog Thumb -->
                            <div class="blog-thumb">
                                <a href="{{ obj.Image.url }}"><img src="{{ obj.Image.url }}" alt=""></a>
                            </div>
                            <!-- Blog Content -->
                            <div class="blog-content">
                                <!-- Meta Info -->
                                <ul class="meta-info d-flex justify-content-between list-unstyled mt-4">
                                    {% if obj.Author|length %}
                                        <li>By <a href="{% url 'core:blogdetail' obj.pk %}">{{ obj.Author }}</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'core:blogdetail' obj.pk %}">{{ obj.Date }}</a></li>
                                </ul>
                                <!-- Blog Title -->
                                <a href="{% url 'core:blogdetail' obj.pk %}">
                                    <h4>{{ obj.Title }}</h4>
                                </a>
                                <p>{{ obj.Tagline }}</p>
                                <!-- Blog Button -->
                                <a class="btn content-btn" href="{% url 'core:blogdetail' obj.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <!-- ***** Blog Area End ***** -->

{% endblock %}

templates/core/contact.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
    <section class="breadcrumb-area overlay-dark d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breamcrumb Content -->
                    <div class="breadcrumb-content text-center">
                        <h2 class="m-0">Contact Us</h2>
                        <ol class="breadcrumb d-flex justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                            <li class="breadcrumb-item active">Contact US</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcrumb Area End ***** -->
    <!-- ***** Contact Area Start ***** -->
    <section class="author-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-8 col-lg-7">
                    <!-- Intro -->
                    <div class="intro text-center">
                        <span>Contact</span>
                        <h3 class="mt-3 mb-0">Get In Touch</h3>
                    </div>
                    <!-- Item Form -->
                    <form  class="item-form card no-hover" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    {{form.name }}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    {{form.email}}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    {{form.subject}}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    {{form.message }}
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn w-100 mt-3 mt-sm-4" type="submit"><i
                                        class="icon-paper-plane mr-2"></i>Send
                                    Message
                                </button>
                            </div>
                        </div>
                    </form>
                    <p class="form-message"></p>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Contact Area End ***** -->
{% endblock %}

templates/core/content.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}
 <!-- ***** Breadcrumb Area Start ***** -->
        <section class="breadcrumb-area overlay-dark d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Breamcrumb Content -->
                        <div class="breadcrumb-content text-center">
                            <h2 class="m-0">Create</h2>
                            <ol class="breadcrumb d-flex justify-content-center">
                                <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{%  url 'core:profile' %}">Profile</a></li>
                                <li class="breadcrumb-item active">Upload Content</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Breadcrumb Area End ***** -->

        <!-- ***** Create Area Start ***** -->
        <section class="author-area">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-12 col-md-7">
                        <!-- Intro -->
                        <div class="intro mt-5 mt-lg-0 mb-4 mb-lg-5">
                            <div class="intro-content">
                                <span>Get Started</span>
                                <h3 class="mt-3 mb-0">Create Item</h3>
                            </div>
                        </div>
                        <!-- Item Form -->
                        <form class="item-form card no-hover" enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="input-group form-group">
                                        <div class="custom-file">
                                          <input type="file" class="custom-file-input" name="Video" required id="id_Video">
                                          <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group mt-3">
                                        <input type="text" class="form-control" name="name" maxlength="200"  id="id_name" placeholder="Item Name" required="required">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <textarea class="form-control" name="description" required id="id_description" placeholder="Description" cols="30" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="col-12 col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="price" id="id_price" placeholder="Item Price" >
                                    </div>
                                </div>


                                <div class="col-12">
                                    <button class="btn w-100 mt-3 mt-sm-4" type="submit">Create Item</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Create Area End ***** -->
{% endblock %}

templates/core/edit_profile.html
{% extends 'base2.html' %}

{% load static %}


{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
    <section class="breadcrumb-area overlay-dark d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breamcrumb Content -->
                    <div class="breadcrumb-content text-center">
                        <h2 class="m-0">Create</h2>
                        <ol class="breadcrumb d-flex justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'core:profile' %}">Profile</a></li>
                            <li class="breadcrumb-item"><a>Edit Profile</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcrumb Area End ***** -->
    <!-- ***** Create Area Start ***** -->
    <section class="author-area">
        <div class="container">
            <div class="row justify-content-between">

                <div class="col-12 col-md-7">
                    <!-- Intro -->
                    <div class="intro mt-5 mt-lg-0 mb-4 mb-lg-5">
                        <div class="intro-content">
                            <span>{{ request.user.username }}</span>
                            <h3 class="mt-3 mb-0">Edit Profile</h3>
                        </div>
                    </div>
                    <!-- Item Form -->
                    <form class="item-form card no-hover" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% include 'accounts/form_errors.html' %}
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    <label> Profile Photo</label>
                                    {{ form.Image }}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    <label> Cover Photo</label>
                                    {{ form.Cover }}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    {{ form.Tagline }}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mt-3">
                                    {{ form.PhoneNumber }}
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn w-100 mt-3 mt-sm-4" type="submit">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Create Area End ***** -->
{% endblock %}

templates/core/profile.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
    <section class="breadcrumb-area overlay-dark d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breamcrumb Content -->
                    <div class="breadcrumb-content text-center">
                        <h2 class="m-0">Create</h2>
                        <ol class="breadcrumb d-flex justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
                            <li class="breadcrumb-item active">{{ request.user.username }}</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcrumb Area End ***** -->

    <!-- ***** Create Area Start ***** -->
    <section class="author-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-12 col-md-4">
                    <!-- Author Profile -->
                    <div class="card no-hover text-center">
                        <div class="image-over">
                            {% if cover|length %}
                               <img style="height: 200px" class="card-img-top" src="{{ cover.url }}" alt="">
                            {% else %}
                                <img class="card-img-top" src="{% static 'assets/img/content/default.png' %}" alt="">
                            {% endif %}

                            <!-- Author -->
                            <div class="author">
                                <div class="author-thumb avatar-lg">
                                    {% if profile|length %}
                                        <img class="rounded-circle" src="{{ profile.url }}"
                                             alt="">
                                    {% else %}
                                        <img class="rounded-circle" src="{% static 'assets/img/content/default.png' %}"
                                             alt="">
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <!-- Card Caption -->
                        <div class="card-caption col-12 p-0">
                            <!-- Card Body -->
                            <div class="card-body mt-4">
                                <h5 class="mb-3">{{ request.user.username }}</h5>
                                <p class="my-3">{{ request.user.profile.Tagline }}</p>
                                <!-- Social Icons -->
                                <div class="row">
                                    <div class="col">
                                        <a class="btn btn-bordered-white btn-smaller"
                                           href="{% url 'core:editprofile' %}">Edit Porfile
                                        </a>
                                    </div>
                                    <div class="col">

                                        <a class="btn btn-bordered-white btn-smaller"
                                           href="{% url 'accounts:signout' %}">Logout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-7">
                    <!-- Intro -->
                    <div class="intro mt-5 mt-lg-0 mb-4 mb-lg-5">
                        <div class="intro-content">
                            <span>Upload Content</span>

                        </div>
                    </div>
                    <!-- Item Form -->
                    <div class="col-12">
                        <a class="btn w-100 mt-3 mt-sm-4 nav-link" href="{% url 'core:content' %}">Upload
                            Content
                        </a>
                    </div>
                    <div class="container" style="margin-top: 5%">
                        <div class="intro mt-5 mt-lg-0 mb-4 mb-lg-5">
                            <div class="intro-content">
                                <span>Your content</span>
                                <h3 class="mt-3 mb-0">Uploaded Content</h3>
                            </div>
                        </div>
                        <div class="row items">
                            {% for obj in obj %}
                                <div class="col-12 col-md-4 item">
                                    <!-- Single Blog -->
                                    <div class="card blog-card">
                                        <!-- Blog Thumb -->
                                        <div class="blog-thumb">
                                            <a href="{{ obj.Video.url }}"><img style="width: 100%; height: 100px"
                                                                               src="{{ obj.Video.url }}"
                                                                               alt=""></a>
                                        </div>
                                        <!-- Blog Content -->
                                        <div class="blog-content">
                                            <!-- Meta Info -->
                                            <ul class="meta-info d-flex justify-content-between list-unstyled mt-4">
                                                <li><a href="">{{ obj.Date }}</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Create Area End ***** -->



{% endblock %}