accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import signin, signup, signout, change_password, password_reset_request, email_message

app_name = "accounts"   # App name for calling Url's in template/Html

urlpatterns = [
    path('', signin, name="login"),
    path('signout', signout, name="signout"),
    path('signup', signup, name="signup"),
    path('change-password', change_password, name="change-password"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('email-activation/', email_message, name="email-activation"),
]

core/urls.py
from django.urls import path
from .views import index, BlogList, BlogDetail, UserProfile, EditProfile, Explore, UploadContent, Contact

app_name = 'core'

urlpatterns = [
    path('', index, name='home'),
    path('explore', Explore, name='explore'),
    path('contact-us', Contact, name='contact'),
    path('upload', UploadContent, name='content'),
    path('blog-list', BlogList, name='bloglist'),
    path('user-profile/', UserProfile, name='profile'),
    path('blog-detail/<int:id>/', BlogDetail, name='blogdetail'),
    path('edit-profile/', EditProfile, name='editprofile'),
]

cranft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('summernote/', include('django_summernote.urls')),
                  path('', include('core.urls')),
                  path('verification/', include('verify_email.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(
                           template_name='accounts/password/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(
                           template_name="accounts/password/password_reset_confirm.html"),
                       name='password_reset_confirm'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='accounts/password/password_reset_complete.html'),
                       name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base2.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Cranft - Blog</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'assets/img/favicon.png' %}">

    <!-- ***** All CSS Files ***** -->

    <!-- Style css -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

</head>

<body class="odd">
<!--====== Preloader Area Start ======-->
<div id="netstorm-preloader" class="netstorm-preloader">
    <!-- Preloader Animation -->
    <div class="preloader-animation">
        <!-- Spinner -->
        <div class="spinner"></div>
        <p class="fw-5 text-center text-uppercase">Loading</p>
    </div>
    <!-- Loader Animation -->
    <div class="loader-animation">
        <div class="row h-100">
            <!-- Single Loader -->
            <div class="col-3 single-loader p-0">
                <div class="loader-bg"></div>
            </div>
            <!-- Single Loader -->
            <div class="col-3 single-loader p-0">
                <div class="loader-bg"></div>
            </div>
            <!-- Single Loader -->
            <div class="col-3 single-loader p-0">
                <div class="loader-bg"></div>
            </div>
            <!-- Single Loader -->
            <div class="col-3 single-loader p-0">
                <div class="loader-bg"></div>
            </div>
        </div>
    </div>
</div>
<!--====== Preloader Area End ======-->

<div class="main">
    <!-- ***** Header Start ***** -->
    <header id="header">
        <!-- Navbar -->
        <nav data-aos="zoom-out" data-aos-delay="800" class="navbar navbar-expand">
            <div class="container header">
                <!-- Navbar Brand-->
                <a class="navbar-brand" href="{% url 'core:home' %}">
                    <img class="navbar-brand-sticky" src="{% static 'assets/img/logo/logo-white.png' %}"
                         alt="sticky brand-logo">
                </a>
                <div class="ml-auto"></div>
                <!-- Navbar -->

                <ul class="navbar-nav items" style="margin-right: 28%">
                    <li class="nav-item active dropdown">
                        <a class="nav-link" href="{% url 'core:home' %}">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'core:explore' %}">Explore</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'core:bloglist' %}">Help Center </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
                    </li>
                     {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'accounts:signup' %}" class="nav-link">Create</a>
                    </li>
                    {% endif %}
                </ul>
                <!-- Navbar Toggler -->
                <ul class="navbar-nav toggle">
                    <li class="nav-item">
                        <a href="#" class="nav-link" data-toggle="modal" data-target="#menu">
                            <i class="fas fa-bars toggle-icon m-0"></i>
                        </a>
                    </li>
                </ul>


                <!-- Navbar Action Button -->
                <ul class="navbar-nav action">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item ml-3">
                            <a href="{% url 'core:profile' %}" class="btn ml-lg-auto btn-bordered-white"><i
                                    class="icon-wallet mr-md-2"></i>Profile</a>
                        </li>
                    {% else %}
                        <li class="nav-item ml-3">
                            <a href="{% url 'accounts:login' %}" class="btn ml-lg-auto btn-bordered-white"><i
                                    class="icon-wallet mr-md-2"></i>Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <!-- ***** Header End ***** -->
    {% block content %}


    {% endblock %}

    <!--====== Footer Area Start ======-->
    <footer class="footer-area">
        <!-- Footer Top -->
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-6 col-lg-3 res-margin">
                        <!-- Footer Items -->
                        <div class="footer-items">
                            <!-- Logo -->
                            <a class="navbar-brand" href="odd-index.html">
                                <img style="width: 20%" src="{% static 'assets/img/logo/logo-white.png' %}" alt="">
                            </a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis non, fugit totam vel
                                laboriosam vitae.</p>
                            <!-- Social Icons -->
                            <div class="social-icons d-flex">
                                <a class="facebook" href="#">
                                    <i class="fab fa-facebook-f"></i>
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a class="twitter" href="#">
                                    <i class="fab fa-twitter"></i>
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a class="google-plus" href="#">
                                    <i class="fab fa-google-plus-g"></i>
                                    <i class="fab fa-google-plus-g"></i>
                                </a>
                                <a class="vine" href="#">
                                    <i class="fab fa-vine"></i>
                                    <i class="fab fa-vine"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-3 res-margin">
                        <!-- Footer Items -->
                        <div class="footer-items">
                            <!-- Footer Title -->
                            <h4 class="footer-title">Useful Links</h4>
                            <ul>
                                <li><a href="#">All NFTs</a></li>
                                <li><a href="#">How It Works</a></li>
                                <li><a href="#">Create</a></li>
                                <li><a href="#">Explore</a></li>
                                <li><a href="#">Privacy &amp; Terms</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-3 res-margin">
                        <!-- Footer Items -->
                        <div class="footer-items">
                            <!-- Footer Title -->
                            <h4 class="footer-title">Community</h4>
                            <ul>
                                <li><a href="#">Help Center</a></li>
                                <li><a href="#">Partners</a></li>
                                <li><a href="#">Suggestions</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Newsletter</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-3">
                        <!-- Footer Items -->
                        <div class="footer-items">
                            <!-- Footer Title -->
                            <h4 class="footer-title">Subscribe Us</h4>
                            <!-- Subscribe Form -->
                            <div class="subscribe-form d-flex align-items-center">
                                <input type="email" class="form-control" placeholder="info@yourmail.com">
                                <button type="submit" class="btn"><i class="icon-paper-plane"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Copyright Area -->
                        <div class="copyright-area d-flex flex-wrap justify-content-center justify-content-sm-between text-center py-4">
                            <!-- Copyright Left -->
                            <div class="copyright-left">&copy;2021 NetStorm, All Rights Reserved.</div>
                            <!-- Copyright Right -->
                            <div class="copyright-right">Made with <i class="fas fa-heart"></i> By <a
                                    href="#">Themeland</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--====== Footer Area End ======-->

    <!--====== Modal Search Area Start ======-->
    <div id="search" class="modal fade p-0">
        <div class="modal-dialog dialog-animated">
            <div class="modal-content h-100">
                <div class="modal-header" data-dismiss="modal">
                    Search <i class="far fa-times-circle icon-close"></i>
                </div>
                <div class="modal-body">
                    <form class="row">
                        <div class="col-12 align-self-center">
                            <div class="row">
                                <div class="col-12 pb-3">
                                    <h2 class="search-title mt-0 mb-3">What are you looking for?</h2>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 input-group mt-4">
                                    <input type="text" placeholder="Enter your keywords">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 input-group align-self-center">
                                    <button class="btn btn-bordered-white mt-3">Search</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--====== Modal Search Area End ======-->

    <!--====== Modal Responsive Menu Area Start ======-->
    <div id="menu" class="modal fade p-0">
        <div class="modal-dialog dialog-animated">
            <div class="modal-content h-100">
                <div class="modal-header" data-dismiss="modal">
                    Menu <i class="far fa-times-circle icon-close"></i>
                </div>
                <div class="menu modal-body">
                    <div class="row w-100">
                        <div class="items p-0 col-12 text-center"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--====== Modal Responsive Menu Area End ======-->

    <!--====== Scroll To Top Area Start ======-->
    <div id="scroll-to-top" class="scroll-to-top">
        <a href="#header" class="smooth-anchor">
            <i class="fas fa-arrow-up"></i>
        </a>
    </div>
    <!--====== Scroll To Top Area End ======-->

</div>


<!-- ***** All jQuery Plugins ***** -->

<!-- jQuery(necessary for all JavaScript plugins) -->
<script src="{% static 'assets/js/vendor/jquery.min.js' %}"></script>

<!-- Bootstrap js -->
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>

<!-- Plugins js -->
<script src="{% static 'assets/js/vendor/all.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/slider.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/countdown.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/shuffle.min.js' %}"></script>

<!-- Active js -->
<script src="{% static 'assets/js/main.js' %}"></script>
</body>


</html>